[package]
name = "nrf-core-fuzz"
version = "0.1.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.nrf-core]
path = "..", features = ["fuzz_expose"]

[[bin]]
name = "decode_value"
path = "fuzz_targets/decode_value.rs"
test = false
doc = false
bench = false